version: "3.9"

services:
  devel:
    build: .
    environment:
      - LOCALSTACK_HOSTNAME=localstack
      - AWS_REGION=ap-northeast-1
    volumes:
      - .:/work
      - target:/work/target
  localstack:
    environment:
      - DEBUG=${DEBUG-}
      - PERSISTENCE=${PERSISTENCE-}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    image: localstack/localstack
    ports:
      - 127.0.0.1:4566:4566
      - 127.0.0.1:4510-4559:4510-4559
    volumes:
      - localstack-store:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
  mysql:
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=local
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - mysql-store:/var/lib/mysql

volumes:
  localstack-store:
  mysql-store:
  target:
