[package]
name = "save-post"
version = "0.1.0"
edition = "2021"

[dependencies]
ytakada-dev-core = { path = "../../ytakada-dev-core", version = "0.1.0" }
lambda_http = "0.7.0"
serde_json = "1.0.86"
tokio = { version = "1.21.2", features = ["full"] }
